# Generated by Django 5.2.7 on 2025-10-24 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloseCallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Time when close call occurred"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when close call was detected"
                    ),
                ),
                ("human_tracking_id", models.CharField(db_index=True, max_length=100)),
                ("human_x", models.FloatField(help_text="Human X coordinate")),
                ("human_y", models.FloatField(help_text="Human Y coordinate")),
                ("human_zone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vehicle_tracking_id",
                    models.CharField(db_index=True, max_length=100),
                ),
                (
                    "vehicle_class",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("vehicle", "Vehicle"),
                            ("pallet_truck", "Pallet Truck"),
                            ("agv", "AGV"),
                        ],
                        help_text="Type of vehicle involved",
                        max_length=20,
                    ),
                ),
                ("vehicle_x", models.FloatField(help_text="Vehicle X coordinate")),
                ("vehicle_y", models.FloatField(help_text="Vehicle Y coordinate")),
                (
                    "vehicle_zone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "distance",
                    models.FloatField(
                        help_text="Distance between human and vehicle in meters",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "distance_threshold",
                    models.FloatField(
                        default=2.0,
                        help_text="Distance threshold used for detection",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "time_window_ms",
                    models.IntegerField(
                        default=250,
                        help_text="Time synchronization window in milliseconds",
                        validators=[django.core.validators.MinValueValidator(50)],
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Close Call Event",
                "verbose_name_plural": "Close Call Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="kpi_closeca_timesta_e0a608_idx"
                    ),
                    models.Index(
                        fields=["human_tracking_id", "vehicle_tracking_id"],
                        name="kpi_closeca_human_t_4877d4_idx",
                    ),
                    models.Index(
                        fields=["vehicle_class"], name="kpi_closeca_vehicle_968e1f_idx"
                    ),
                    models.Index(
                        fields=["distance"], name="kpi_closeca_distanc_bcaa99_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique tracking ID per object trajectory from CSV 'id' column.",
                        max_length=100,
                    ),
                ),
                (
                    "object_class",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("vehicle", "Vehicle"),
                            ("pallet_truck", "Pallet Truck"),
                            ("agv", "AGV"),
                        ],
                        db_index=True,
                        help_text="Object classification from CSV 'type' column.",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Detection timestamp from CSV 'timestamp' column (ISO 8601 UTC).",
                    ),
                ),
                ("x", models.FloatField(help_text="Local X coordinate in meters.")),
                ("y", models.FloatField(help_text="Local Y coordinate in meters.")),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Heading angle in degrees (0–360). Null if unavailable.",
                        null=True,
                    ),
                ),
                (
                    "vest",
                    models.BooleanField(
                        blank=True,
                        help_text="Safety vest status from CSV 'vest' column. Only meaningful for humans.",
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Instantaneous speed in m/s from CSV 'speed' column.",
                        null=True,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Zone identifier from CSV 'area' column.",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("timestamp",),
                "indexes": [
                    models.Index(
                        fields=["object_class", "timestamp"],
                        name="kpi_detecti_object__986816_idx",
                    ),
                    models.Index(
                        fields=["zone", "timestamp"], name="kpi_detecti_zone_ae2750_idx"
                    ),
                    models.Index(
                        fields=["vest", "timestamp"], name="kpi_detecti_vest_a13dc5_idx"
                    ),
                    models.Index(
                        fields=["timestamp", "object_class"],
                        name="kpi_detecti_timesta_d9845d_idx",
                    ),
                    models.Index(fields=["x", "y"], name="kpi_detecti_x_f40eaa_idx"),
                ],
            },
        ),
    ]
