# Generated by Django 5.2.7 on 2025-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        help_text="From CSV 'id' column: unique tracking ID per object trajectory.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "object_class",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("vehicle", "Vehicle"),
                            ("pallet_truck", "Pallet Truck"),
                            ("agv", "AGV"),
                        ],
                        db_index=True,
                        help_text="From CSV 'type' column: e.g., 'human', 'vehicle', 'pallet_truck', 'agv'.",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="From CSV 'timestamp' column (ISO 8601 UTC).",
                    ),
                ),
                ("x", models.FloatField(help_text="Local X coordinate in meters.")),
                ("y", models.FloatField(help_text="Local Y coordinate in meters.")),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Heading angle in degrees (0–360). May be 0.0 if unavailable.",
                        null=True,
                    ),
                ),
                (
                    "vest",
                    models.BooleanField(
                        blank=True,
                        help_text="From CSV 'vest' column: True if '1', False if '0'. Only meaningful for 'human'.",
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Instantaneous speed in m/s (from CSV 'speed' column).",
                        null=True,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="From CSV 'area' column: named or numeric zone identifier.",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("timestamp",),
                "indexes": [
                    models.Index(
                        fields=["object_class", "timestamp"],
                        name="kpi_detecti_object__986816_idx",
                    ),
                    models.Index(
                        fields=["zone", "timestamp"], name="kpi_detecti_zone_ae2750_idx"
                    ),
                    models.Index(
                        fields=["vest", "timestamp"], name="kpi_detecti_vest_a13dc5_idx"
                    ),
                    models.Index(
                        fields=["timestamp", "object_class"],
                        name="kpi_detecti_timesta_d9845d_idx",
                    ),
                ],
            },
        ),
    ]
