# Generated by Django 5.2.7 on 2025-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="heading",
            field=models.FloatField(
                blank=True,
                help_text="Heading angle in degrees (0–360). Null if unavailable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="object_class",
            field=models.CharField(
                choices=[
                    ("human", "Human"),
                    ("vehicle", "Vehicle"),
                    ("pallet_truck", "Pallet Truck"),
                    ("agv", "AGV"),
                ],
                db_index=True,
                help_text="Object classification from CSV 'type' column.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="speed",
            field=models.FloatField(
                blank=True,
                help_text="Instantaneous speed in m/s from CSV 'speed' column.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                help_text="Detection timestamp from CSV 'timestamp' column (ISO 8601 UTC).",
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="tracking_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique tracking ID per object trajectory from CSV 'id' column.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="vest",
            field=models.BooleanField(
                blank=True,
                help_text="Safety vest status from CSV 'vest' column. Only meaningful for humans.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="zone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Zone identifier from CSV 'area' column.",
                max_length=50,
                null=True,
            ),
        ),
    ]
