# Generated by Django 5.2.7 on 2025-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0003_closecallevent"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["x", "y"], name="kpi_detecti_x_f40eaa_idx"),
        ),
    ]
